### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by pacbidouandco** [YunoHost-Apps/actual_ynh#40]
Hello, I'm currently using Actual Budget with Yunohost ans I would Like to reset my password. I haven't found any command line to do that. Can you help me with that please ? Thank you

**Comment by Quiwy** [comment]
Go to `/var/www/actual`.
And run `npm run reset-password`.

Just tried it, seems working.

**Comment by pacbidouandco** [comment]
hi,

I tried this command line, but it says : npm command not found

What npm means ?

Thanks for your help



16 septembre 2024 à 16:56 "Quiwy" ***@***.***> a écrit:

**Comment by Quiwy** [comment]
Sorry, it seems I have npm installed.

Just tested on a fresh yunohsot virtualbox install. Here you can find how to reset the password :

1. get node version loaded into the path ` PATH=/opt/node_n/n/versions/node/18/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
2. reset the password : `sudo PATH="$PATH"  /opt/node_n/n/versions/node/18/bin/npm run --prefix /var/www/actual reset-password`

It should work.
Let me know if it doesn't

**Comment by Quiwy** [comment]
@pacbidouandco : could you try the solution ?

**Comment by Quiwy** [comment]
Could you close your issue please @pacbidouandco :smile:
