### ISSUE TITLE
lines are overlapping...

### ISSUE THREAD

**Issue by pacbidouandco** [YunoHost-Apps/actual_ynh#53]
Hi 

Do you have the same thing? The lines are overlapping...

![screenshot](https://github.com/user-attachments/assets/7d326831-3894-447f-9f08-ee99103c785c)

Thank you for your help

**Comment by Quiwy** [comment]
Hi @pacbidouandco ,
It's an [upstream bug of 2024.11.0 version](https://github.com/actualbudget/actual/issues/3869).

Should be fixed when #49 is merged (hopefully this week).

**Comment by Quiwy** [comment]
Just updated, I confirm issue is fixed with version 24.12.0~ynh2 .

**Comment by pacbidouandco** [comment]
Thanks a lot, great job
